## Server properties
server:
  port: 8080

## Primary/Target Database Properties
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/customerdb
    username: root
    password: admin123
  jpa.hibernate.ddl-auto: none
  jpa.show-sql: true

## Source Database Properties
customer:
  datasource:
    host: 127.0.0.1
    port: 3305
    database: customerdb
    username: root
    password: admin123

  ## Logging properties
logging:
  level:
    root: INFO
    io:
      debezium:
        mysql:
          BinlogReader: INFO
    com:
      baeldung:
        libraries:
          debezium: DEBUG